# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CGI-Wiki-Plugin-Locator-Grid
version:      0.03
version_from: lib/CGI/Wiki/Plugin/Locator/Grid.pm
installdirs:  site
requires:
    Carp:                          0
    CGI::Wiki:                     0.36
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
